"""Auto-generated by sync_schemas from YAML config. Do not edit manually."""

from typing import List, Optional

from pydantic import BaseModel, Field


class GeologyExtractionResult(BaseModel):
    """Domain-specific fields for geology reports."""

    rock_types: List[str] = Field(default_factory=list, description='岩石類型')
    formations: List[str] = Field(default_factory=list, description='地層名稱')
    geological_age: Optional[str] = Field(default=None, description='地質年代')
    temperature_gradient: Optional[str] = Field(default=None, description='溫度梯度')
    drilling_depth: Optional[str] = Field(default=None, description='鑽井深度')
    well_names: List[str] = Field(default_factory=list, description='井名列表')
    geothermal_assessment: Optional[str] = Field(default=None, description='地熱資源評估')
    exploration_methods: List[str] = Field(default_factory=list, description='探勘方法')
