"""Auto-generated by sync_schemas from YAML config. Do not edit manually."""

from typing import List, Optional

from pydantic import BaseModel, Field


class CoreExtractionResult(BaseModel):
    """Fields extracted from every document regardless of genre."""

    title: Optional[str] = Field(default=None, description='文件標題')
    authors: List[str] = Field(default_factory=list, description='作者列表')
    institution: Optional[str] = Field(default=None, description='執行單位')
    date: Optional[str] = Field(default=None, description='日期')
    year: Optional[int] = Field(default=None, description='年度（整數）')
    abstract: Optional[str] = Field(default=None, description='摘要')
    key_findings: List[str] = Field(default_factory=list, description='關鍵發現（列表）')
    llm_recommendations: List[str] = Field(default_factory=list, description='基於內容的延伸建議（列表）')
    llm_commentary: Optional[str] = Field(default=None, description='你對這段內容的專業評析')
    confidence_score: float = Field(default=0.0, ge=0.0, le=1.0, description='信心分數 (0.0-1.0)')
    thinking: Optional[str] = Field(default=None, description='推理過程')
