"""Generate Pydantic model files from YAML schema definitions.

Usage:
    uv run python -m lmetl.tools.sync_schemas configs/base.yaml
    uv run python -m lmetl.tools.sync_schemas --check configs/base.yaml
"""

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

from lmetl.utils.config import load_lmetl_config
from lmetl.utils.schema_loader import _parse_type, _reject_nested_list_object

# Project root: src/lmetl/tools/sync_schemas.py → src/lmetl/
_PACKAGE_ROOT = Path(__file__).parent.parent
_SCHEMAS_DIR = _PACKAGE_ROOT / "schemas"
_GENRES_DIR = _SCHEMAS_DIR / "genres"


def _item_class_name(field_name: str) -> str:
    """Nested model class name for a list[object] field (wells → WellsItem)."""
    return field_name.capitalize() + "Item"


def _field_to_pydantic_line(field: Dict[str, Any]) -> str:
    """Convert a single YAML field definition to a Pydantic field line."""
    name = field["name"]
    type_str = field.get("type", "str?")
    description = field.get("description", "")
    constraints = field.get("constraints", {})

    if type_str == "list[object]":
        item_class = _item_class_name(name)
        return (
            f"    {name}: List[{item_class}] = "
            f"Field(default_factory=list, description={description!r})"
        )

    base_type, _, is_optional, is_list = _parse_type(type_str)

    # Build type annotation
    base_name = base_type.__name__
    if is_list:
        annotation = f"List[{base_name}]"
    elif is_optional:
        annotation = f"Optional[{base_name}]"
    else:
        annotation = base_name

    # Build Field() kwargs
    field_parts: List[str] = []

    if is_list:
        field_parts.append("default_factory=list")
    elif is_optional:
        default = constraints.get("default", None)
        field_parts.append(f"default={default!r}")
    elif "default" in constraints:
        field_parts.append(f"default={constraints['default']!r}")

    for key in ("ge", "le", "gt", "lt"):
        if key in constraints:
            field_parts.append(f"{key}={constraints[key]!r}")

    if description:
        field_parts.append(f"description={description!r}")

    field_str = ", ".join(field_parts)
    return f"    {name}: {annotation} = Field({field_str})"


def generate_model_code(
    class_name: str,
    docstring: str,
    fields: List[Dict[str, Any]],
) -> str:
    """Generate complete Python source for a Pydantic model.

    list[object] fields produce a nested ``{Field}Item`` model class emitted
    before the main class (depth-1 only; see all_info design, lamp §9e).
    """
    entity_fields = [f for f in fields if f.get("type") == "list[object]"]
    for field in entity_fields:
        _reject_nested_list_object(field)
    nested_field_defs = [nf for f in entity_fields for nf in f.get("fields", [])]

    # Determine needed imports (nested definitions count too)
    all_defs = fields + nested_field_defs
    needs_list = any(f.get("type", "").startswith("list[") for f in all_defs)
    needs_optional = any(f.get("type", "").endswith("?") for f in all_defs)

    typing_imports = []
    if needs_list:
        typing_imports.append("List")
    if needs_optional:
        typing_imports.append("Optional")

    lines = [
        '"""Auto-generated by sync_schemas from YAML config. Do not edit manually."""',
        "",
    ]

    if typing_imports:
        lines.append(f"from typing import {', '.join(sorted(typing_imports))}")
        lines.append("")

    lines.extend([
        "from pydantic import BaseModel, Field",
        "",
    ])

    for field in entity_fields:
        identity = field.get("identity")
        identity_note = f" (identity: {identity})" if identity else ""
        lines.extend([
            "",
            f"class {_item_class_name(field['name'])}(BaseModel):",
            f'    """Nested items for {field["name"]}{identity_note}."""',
            "",
        ])
        for nested in field.get("fields", []):
            lines.append(_field_to_pydantic_line(nested))
        lines.append("")

    lines.extend([
        "",
        f"class {class_name}(BaseModel):",
        f'    """{docstring}"""',
        "",
    ])

    for field in fields:
        lines.append(_field_to_pydantic_line(field))

    lines.append("")  # trailing newline
    return "\n".join(lines)


def sync_schemas(config_path: str, check_only: bool = False) -> bool:
    """Generate or check Pydantic models from YAML config.

    Returns True if everything is in sync, False otherwise.
    """
    config = load_lmetl_config(config_path)
    schemas = config.get("schemas", {})

    all_synced = True

    # Core schema
    core_def = schemas.get("core", {})
    core_fields = core_def.get("fields", [])
    if core_fields:
        core_code = generate_model_code(
            class_name="CoreExtractionResult",
            docstring="Fields extracted from every document regardless of genre.",
            fields=core_fields,
        )
        core_path = _SCHEMAS_DIR / "core.py"
        all_synced &= _write_or_check(core_path, core_code, check_only)

    # Genre schemas
    genres = schemas.get("genres", {})
    for genre_name, genre_def in genres.items():
        genre_fields = genre_def.get("fields", [])
        if not genre_fields:
            continue

        class_name = genre_name.capitalize() + "ExtractionResult"
        docstring = f"Domain-specific fields for {genre_name} reports."

        genre_code = generate_model_code(
            class_name=class_name,
            docstring=docstring,
            fields=genre_fields,
        )
        genre_path = _GENRES_DIR / f"{genre_name}.py"
        all_synced &= _write_or_check(genre_path, genre_code, check_only)

    return all_synced


def _write_or_check(path: Path, expected: str, check_only: bool) -> bool:
    """Write file or check if it matches expected content."""
    if check_only:
        if not path.exists():
            print(f"MISSING: {path}")
            return False
        current = path.read_text()
        if current == expected:
            print(f"OK: {path}")
            return True
        else:
            print(f"OUT OF SYNC: {path}")
            # Show first difference
            current_lines = current.splitlines()
            expected_lines = expected.splitlines()
            for i, (c, e) in enumerate(zip(current_lines, expected_lines)):
                if c != e:
                    print(f"  Line {i + 1}:")
                    print(f"    current:  {c}")
                    print(f"    expected: {e}")
                    break
            return False
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected)
        print(f"WROTE: {path}")
        return True


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sync Pydantic models from YAML schema definitions."
    )
    parser.add_argument("config", help="Path to pipeline YAML config")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check mode: verify files are in sync without writing (for CI)",
    )
    args = parser.parse_args()

    synced = sync_schemas(args.config, check_only=args.check)

    if args.check and not synced:
        print("\nSchema files are out of sync with YAML config.")
        print("Run: uv run python -m lmetl.tools.sync_schemas", args.config)
        sys.exit(1)
    elif not args.check:
        print("\nDone. Schema files updated.")


if __name__ == "__main__":
    main()
